#!/usr/bin/with-contenv sh

action="$1"
if [ -z "$action" ]; then
	action="run"
fi

source lego-config

if [ "$action" = "renew" ]; then
	action="renew --days $LEGO_RENEW_DAYS"
fi
# CLOUDFLARE_EMAIL, CLOUDFLARE_API_KEY must be set with the apropriate credentials
/usr/bin/lego $LEGO_ARGS $action

if [ -f "$LEGO_HOOKS_DIR/$action" ]; then
	exec "$LEGO_HOOKS_DIR/$action"
fi