#!/bin/sh

OUTPUT=""

printf '::'
while read -r line; do
	OUTPUT="$OUTPUT$line\n"
	echo "$line" | grep "$1" > /dev/null
	if [ "$?" == "0" ]; then
		printf ":: Done\n"
		exit 0
	fi
	printf '.'
done
printf '>> ERROR\n'
echo -e "$OUTPUT"
exit 1
