#!/bin/sh

if [ -z "$GIT_USERNAME" ]; then
  echo '\$GIT_USERNAME Empty' >2
  exit 1
fi

if [ -z "$GIT_PASSWD" ]; then
  echo '\$GIT_PASSWD Empty' >2
  exit 1
fi

printf "username=$GIT_USERNAME\npassword=$PASSWORD\n"
