#!/usr/bin/with-contenv sh

domains="$(echo $LEGO_DOMAINS | sed 's/*/_/g')"
for i in ${domains//,/ }; do
	echo "Installing certificate for $i"
    cert_path="/$LEGO_PATH/certificates/${i}.pem"
    output="/etc/haproxy/certs.d/${i}.pem"
    cp "$cert_path" "$output"
done

exec reload-haproxy
