#!/usr/bin/with-contenv sh

# CLOUDFLARE_EMAIL, CLOUDFLARE_API_KEY must be set with the apropriate credentials

issue_cert() {
	echo  "$1 $2"
}

action="$1"
if [ -z "$action" ]; then
	action="run"
fi

source lego-config

if [ "$action" = "renew" ]; then
	action="renew --days $LEGO_RENEW_DAYS"
fi

/usr/bin/lego $LEGO_ARGS $action | wait-grep "Server responded with a certificate"
if [ "$?" != 0 ]; then
	exit  "$?"
fi
if [ -f "$LEGO_HOOKS_DIR/$action" ]; then
	echo "Executing Hook $LEGO_HOOKS_DIR/$action"
	exec "$LEGO_HOOKS_DIR/$action"
fi
