#!/bin/sh

OUTPUT=""

printf '::'
while read -r line; do
	OUTPUT="$OUTPUT$line\n"
	echo "$line"
	echo "$line" | grep "$1" > /dev/null
	if [ "$?" == "0" ]; then
		exit 0
	fi
done
printf '>> ERROR\n'
echo -e "$OUTPUT"
exit 1
