#!/bin/sh

touch /etc/authelia/acl.yaml
/usr/local/bin/yam /etc/authelia/base.yaml /etc/authelia/acl.yaml $AUTHELIA_EXTRA_CONFIG > /etc/authelia/configuration.yaml

exec /app/entrypoint.sh --config /etc/authelia/configuration.yaml
