name: Bump Versions
description: Bump image version based on changes and updates
inputs:
  changes:
    description: images with file changes
  updates:
    description: images with updated dependencies
runs:
  using: 'node12'
  main: 'index.js'