name: Images

on:
  push:
    branches:
      - master
      # For when we're swapped
      # - trunk
    tags:
      - '*-v*'
jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Discover Changes
        id: discover
        uses: ./.github/actions/discover-changes
      - name: Build Images
        id: build
        uses: ./.github/actions/build-images
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          changes: ${{ steps.discover.outputs.changes }}
      - name: Publish Images
        id: publish
        uses: ./.github/actions/publish-images
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_token: ${{ secrets.DOCKER_TOKEN }}
          images: ${{ steps.build.outputs.images }}
