name: build

on:
  push: {}
  workflow_dispatch: {}
    # branches:
    #   - trunk
    # tags:
    #   - '*-v*'
jobs:
  images:
    name: build images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker.io
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install shoreman
        run: pip install --user git+https://github.com/tmacro/shoreman.git

      - name: Print changes
        run: shoreman changes
