name: build

on:
  push: {}
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: false
        default: HEAD
        description: Reference to build
    # branches:
    #   - trunk
    # tags:
    #   - '*-v*'
jobs:
  images:
    env:
      REF: ${{ inputs.ref }}
    name: build images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.REF }}
          fetch-depth: 2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install shoreman
        run: pip install --user git+https://github.com/tmacro/shoreman.git

      - name: Print changes
        run: shoreman --verbose changes

      - name: Build and push images
        run: shoreman build --push
